49 project make behat tests for plugins
AAU-P5-Moodle/moodle-2 pull request #102
Opened 2024-12-04 18:14 UTC by mikk771h

Kør php admin/tool/behat/cli/run.php --tags=@homework i Docker terminal for alle tests, eller med tag @mod_homework eller @block_homework

2024-12-04 19:07 UTC, AllanVester commented
Der er blevet lavet ændringer i [block_homework](https://github.com/AAU-P5-Moodle/moodle-2/pull/102/files#diff-20cd97d3b1e5932d1d462f58032f7e3900d09303f91ea7c698f50e4c5afcdacb), som har fjernet en del kode mht. bl.a. pdf_reader og getstats().

https://github.com/AAU-P5-Moodle/moodle-2/pull/102/files#diff-20cd97d3b1e5932d1d462f58032f7e3900d09303f91ea7c698f50e4c5afcdacbL220-L308

Tænker den hurtigste måde at fikse det på er, at copy-paste [hele koden i block_homework.php fra main](https://github.com/AAU-P5-Moodle/moodle-2/blob/main/server/moodle/blocks/homework/block_homework.php) ind i din [branch](https://github.com/AAU-P5-Moodle/moodle-2/blob/49-project-make-behat-tests-for-plugins/server/moodle/blocks/homework/block_homework.php).

Udover det, så kan jeg se, at du har ændret i følgende filer:
- [behat.yml.dist](https://github.com/AAU-P5-Moodle/moodle-2/pull/102/files#diff-481aaeef12be72c3a9ad97cb1094446aff8e559936d09439053fb8636b69ab29) - tænker at du har gjort for hurtigere at kunne teste Behat på homework, men tænker at den nok skal ændres tilbage, så de næste, som får Moodle, ikke bliver forvirret.
- [behat_init_context.php](https://github.com/AAU-P5-Moodle/moodle-2/pull/102/files#diff-87bcdb02ed80cfc2a214eae16a1eecea4c84ffb880f07b94d8483e6206516d00) - tænker ikke at det var meningen at du vil commite denne fil.
- [config.php](https://github.com/AAU-P5-Moodle/moodle-2/pull/102/files#diff-1aa15f4c627adfa4ff13ad1d3ee4871d3db9ed60c6d3639345e75302fa9d02c4) - denne fil burde ikke have været commitet, da det resulterer i vores GitHub Actions checks fejler.

Når disse filer er blevet ændret, så vil vi gerne review dine Behat tests 😀.

2024-12-05 15:10 UTC, mikk771h commented
har fjernet det random mellemrum i behat_init_context.php, fjernet paths fra behat.yml.dist og opdateret block_homework.php. er config.php fjernet helt fra main? den har tidligere eksisteret. ændringerne i den er nødvendige for at behat kan køre testene.

2024-12-06 07:54 UTC, AllanVester commented
> har fjernet det random mellemrum i behat_init_context.php, fjernet paths fra behat.yml.dist og opdateret block_homework.php. er config.php fjernet helt fra main? den har tidligere eksisteret. ændringerne i den er nødvendige for at behat kan køre testene.

config.php er helt fjernet fra main, da den kommer med Docker setup'et. Vi sætter selv Selenium op under review, så det behøver du ikke at tænke på

2024-12-06 08:04 UTC, mikk771h commented
så er den fjernet

2024-12-06 08:31 UTC, AllanVester requested changes

2024-12-06 08:31 UTC, AllanVester commented on server/moodle/blocks/homework/tests/behat/block_homework_feed.feature
> +    And I click on "2025" "option"
Vi har fundet nogle fejl ved Behat tests i Firefox.

Du kan ændre dine tests, så de ser sådan her ud:
```suggestion
    And I click on "duedateselector[enabled]" "checkbox"
    And I select "15" from the "duedateselector[day]" singleselect
    And I select "October" from the "duedateselector[month]" singleselect
    And I select "2025" from the "duedateselector[year]" singleselect
```

Nu vil der ske det samme, og både Chrome og Firefox vil godkende det

2024-12-06 08:31 UTC, AllanVester commented on server/moodle/blocks/homework/tests/behat/block_homework_feed.feature
> +    And I click on "2026" "option"
Det samme her:
```suggestion
    And I click on "duedateselector[enabled]" "checkbox"
    And I select "15" from the "duedateselector[day]" singleselect
    And I select "October" from the "duedateselector[month]" singleselect
    And I select "2026" from the "duedateselector[year]" singleselect
```

2024-12-06 08:31 UTC, AllanVester commented on server/moodle/blocks/homework/tests/behat/block_homework_feed.feature
> +    And I click on "Due Date" "option"
Tænker måske at det er bedre at afslutte med at logge ud og det følgende kode ikke bidrager til testsne, vil jeg nok bare fjerne:
```
Then I click on "sort" "select"
And I click on "Due Date" "option"
```
Så nu vil det se sådan her ud:
```suggestion
    And I should see "2025" in the "Homework" "block"
    And I should see "2026" in the "Homework" "block"
    And I log out
```

2024-12-06 08:50 UTC, mikk771h commented
lavet ændringer

2024-12-06 08:57 UTC, AllanVester approved these changes

2024-12-06 09:31 UTC, merged