31 homework student feature pretify the preparation feed
AAU-P5-Moodle/moodle-2 pull request #69
Opened 2024-11-21 11:21 UTC by Not-Brundle

2024-11-25 12:05 UTC, Skjodt reviewed
Husk at tilføje et billede som vi har aftalt til PO møderne, da jeg har ingen mulighed for at se, hvad jeg skal forvente. Fik nedenstående billede så går ud fra at det er det? Kan I bekræfte?

![image](https://github.com/user-attachments/assets/6e51b0b1-475c-4b83-a7a8-4ede61c2e7ce)

2024-11-25 18:13 UTC, Not-Brundle commented
Dette er det jeg har lavet det udfra. På det tidspunkt eksisterede time knappen ikke. Men det billede du har ser også rigtigt ud.
![HomeFeed](https://github.com/user-attachments/assets/8103652e-7788-4559-8c5b-ce2b551f22ce)

2024-11-26 08:55 UTC, Skjodt commented
> Dette er det jeg har lavet det udfra. På det tidspunkt eksisterede filter knapperne og time knappen ikke. Men det billede du har ser rigtigt ud. ![HomeFeed](https://private-user-images.githubusercontent.com/113098403/389649592-8103652e-7788-4559-8c5b-ce2b551f22ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDgyNzIsIm5iZiI6MTczMjYwNzk3MiwicGF0aCI6Ii8xMTMwOTg0MDMvMzg5NjQ5NTkyLTgxMDM2NTJlLTc3ODgtNDU1OS04YzViLWNlMmI1NTFmMjJjZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNzU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjQwZTQ1OTNhMDlmYmQ2ODgzZTFjOWI4ZGExODJhMWMzNjJjZmEwOTA2ZDM0ZGE2YzMxNzJkNGRlZTgxNjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UxrvY8a5vZApxOx3CTFERT9FYHKJABBrDCq6nqkXYnA)

Den henter slet ikke homework files, så tænker I skal have merged main ind, når jeres branch (PDF-word-count-reader-with-new-database) er merged i main

2024-11-26 08:57 UTC, Skjodt requested changes
Læs tidligere besked

2024-11-28 12:57 UTC, Skjodt approved these changes

2024-11-28 15:21 UTC, merged