64 homework teacherpretify editor modal
AAU-P5-Moodle/moodle-2 pull request #73
Opened 2024-11-22 03:50 UTC by Not-Brundle

2024-11-25 11:46 UTC, Skjodt requested changes
Can you show a picture of how the modal looks?

Currently, with main branch and your branch, the .css you have uploaded is not utilized - have you forgotten to upload the updated page file including the styling or something?

2024-11-27 17:30 UTC, Not-Brundle commented
Nu burde alt fungere rigtigt. Jeg havde gjort forkert på det forrige commit. Det burde se ud som på det vedhæftede billede.
![editModalScreenshot](https://github.com/user-attachments/assets/53459a8c-59bf-439d-b3d0-1890cde57a98)

2024-11-28 13:12 UTC, Skjodt requested changes
Egentlig en god ide, at få editor pagen til også at have samme styling som view page, og synes også vi skal have det tilføjet, men denne opgave omhandler primært editor modalen:

![image](https://github.com/user-attachments/assets/9b960152-c352-4a45-b477-3eccb0f48cc3)

Ovenstående er hvordan den ser ud for mig, men det er uændret ift. hvordan den blev lavet i første omgang.

2024-12-04 01:14 UTC, Not-Brundle commented
Skulle gerne se sådan her ud nu.
![homeworkchooser](https://github.com/user-attachments/assets/e9ab99af-1710-4b5b-8a93-ee4d2e75d90c)

2024-12-04 10:01 UTC, Skjodt approved these changes
Ser godt ud. har fikset så tests også pass

2024-12-04 10:01 UTC, merged